-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 10:38:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salas` (
  ` id` INT NULL,
  `numero_sala` VARCHAR(8) NULL,
  `andar_sala` VARCHAR(8) NULL,
  `capacidade_sala` INT NULL,
  PRIMARY KEY (` id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  ` id` INT NULL,
  `turno_turma` VARCHAR(5) NULL,
  `data_inicio` DATE NULL,
  `data_final` DATE NULL,
  `salas_ id` INT NOT NULL,
  PRIMARY KEY (` id`, `salas_ id`),
  INDEX `fk_turmas_salas1_idx` (`salas_ id` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_salas1`
    FOREIGN KEY (`salas_ id`)
    REFERENCES `mydb`.`salas` (` id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diciplinas` (
  ` id` INT NULL,
  `nome_diciplina` VARCHAR(45) NULL,
  `carga_horaria` VARCHAR(45) NULL,
  `descricao_diciplina` TEXT NULL,
  `turmas_ id` INT NOT NULL,
  `turmas_salas_ id` INT NOT NULL,
  PRIMARY KEY (` id`, `turmas_ id`, `turmas_salas_ id`),
  INDEX `fk_diciplinas_turmas1_idx` (`turmas_ id` ASC, `turmas_salas_ id` ASC) VISIBLE,
  CONSTRAINT `fk_diciplinas_turmas1`
    FOREIGN KEY (`turmas_ id` , `turmas_salas_ id`)
    REFERENCES `mydb`.`turmas` (` id` , `salas_ id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matriculas` (
  ` id` INT NULL,
  `data_matricula` DATE NULL,
  `local_matricula` VARCHAR(80) NULL,
  PRIMARY KEY (` id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  ` id` INT NULL,
  `nome_curso` VARCHAR(45) NULL,
  `data_inicio` DATE NULL,
  `data_final` DATE NULL,
  `descricao_curso` TEXT NULL,
  `carga_horaria` VARCHAR(45) NULL,
  `requisitos` VARCHAR(255) NULL,
  `diciplinas_ id` INT NOT NULL,
  `matriculas_ id` INT NOT NULL,
  PRIMARY KEY (` id`, `diciplinas_ id`, `matriculas_ id`),
  INDEX `fk_cursos_diciplinas1_idx` (`diciplinas_ id` ASC) VISIBLE,
  INDEX `fk_cursos_matriculas1_idx` (`matriculas_ id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_diciplinas1`
    FOREIGN KEY (`diciplinas_ id`)
    REFERENCES `mydb`.`diciplinas` (` id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_matriculas1`
    FOREIGN KEY (`matriculas_ id`)
    REFERENCES `mydb`.`matriculas` (` id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  ` id` INT NULL,
  `nome_aluno` VARCHAR(45) NULL,
  `cpf_aluno` VARCHAR(14) NULL,
  `telefone_aluno` VARCHAR(12) NULL,
  `email_aluno` VARCHAR(45) NULL,
  `endereco_aluno` VARCHAR(80) NULL,
  `sexo_aluno` ENUM('M', 'F') NULL,
  `dt_nasc_aluno` DATE NULL,
  `matriculas_ id` INT NOT NULL,
  PRIMARY KEY (` id`, `matriculas_ id`),
  INDEX `fk_alunos_matriculas1_idx` (`matriculas_ id` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_matriculas1`
    FOREIGN KEY (`matriculas_ id`)
    REFERENCES `mydb`.`matriculas` (` id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores` (
  ` id` INT NULL,
  `nome_professor` VARCHAR(45) NULL,
  `cpf_professor` VARCHAR(14) NULL,
  `telefone_professor` VARCHAR(12) NULL,
  `email_professor` VARCHAR(45) NULL,
  `endereco_professor` VARCHAR(80) NULL,
  `sexo_professor` ENUM('M', 'F') NULL,
  `dt_nasc_professor` DATE NULL,
  `valor_hora` INT NULL,
  PRIMARY KEY (` id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituicao` (
  ` id` INT NULL,
  `nome_instituicao` VARCHAR(45) NULL,
  `cnpj_instituicao` VARCHAR(14) NULL,
  `endereco_instituicao` VARCHAR(80) NULL,
  `email_instituicao` VARCHAR(45) NULL,
  `telefone_instituicao` VARCHAR(12) NULL,
  `cursos_ id` INT NOT NULL,
  `cursos_ id1` INT NOT NULL,
  `cursos_diciplinas_ id` INT NOT NULL,
  PRIMARY KEY (` id`, `cursos_ id`, `cursos_ id1`, `cursos_diciplinas_ id`),
  INDEX `fk_instituicao_cursos1_idx` (`cursos_ id1` ASC, `cursos_diciplinas_ id` ASC) VISIBLE,
  CONSTRAINT `fk_instituicao_cursos1`
    FOREIGN KEY (`cursos_ id1` , `cursos_diciplinas_ id`)
    REFERENCES `mydb`.`cursos` (` id` , `diciplinas_ id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facilitadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facilitadores` (
  ` id` INT NULL,
  `nome_facilitador` VARCHAR(45) NULL,
  `cpf_facilitador` VARCHAR(14) NULL,
  `telefone_facilitador` VARCHAR(12) NULL,
  `email_facilitador` VARCHAR(45) NULL,
  `endereco_facilitador` VARCHAR(80) NULL,
  `sexo_facilitador` ENUM('M', 'F') NULL,
  `dt_nasc_facilitador` DATE NULL,
  `valor_hora_facilitador` INT NULL,
  PRIMARY KEY (` id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos_has_turmas` (
  `alunos_ id` INT NOT NULL,
  `turmas_ id` INT NOT NULL,
  `turmas_salas_ id` INT NOT NULL,
  PRIMARY KEY (`alunos_ id`, `turmas_ id`, `turmas_salas_ id`),
  INDEX `fk_alunos_has_turmas_turmas1_idx` (`turmas_ id` ASC, `turmas_salas_ id` ASC) VISIBLE,
  INDEX `fk_alunos_has_turmas_alunos1_idx` (`alunos_ id` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_has_turmas_alunos1`
    FOREIGN KEY (`alunos_ id`)
    REFERENCES `mydb`.`alunos` (` id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_turmas_turmas1`
    FOREIGN KEY (`turmas_ id` , `turmas_salas_ id`)
    REFERENCES `mydb`.`turmas` (` id` , `salas_ id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores_has_turmas` (
  `professores_ id` INT NOT NULL,
  `turmas_ id` INT NOT NULL,
  `turmas_salas_ id` INT NOT NULL,
  PRIMARY KEY (`professores_ id`, `turmas_ id`, `turmas_salas_ id`),
  INDEX `fk_professores_has_turmas_turmas1_idx` (`turmas_ id` ASC, `turmas_salas_ id` ASC) VISIBLE,
  INDEX `fk_professores_has_turmas_professores1_idx` (`professores_ id` ASC) VISIBLE,
  CONSTRAINT `fk_professores_has_turmas_professores1`
    FOREIGN KEY (`professores_ id`)
    REFERENCES `mydb`.`professores` (` id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_has_turmas_turmas1`
    FOREIGN KEY (`turmas_ id` , `turmas_salas_ id`)
    REFERENCES `mydb`.`turmas` (` id` , `salas_ id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facilitadores_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facilitadores_has_turmas` (
  `facilitadores_ id` INT NOT NULL,
  `turmas_ id` INT NOT NULL,
  `turmas_salas_ id` INT NOT NULL,
  PRIMARY KEY (`facilitadores_ id`, `turmas_ id`, `turmas_salas_ id`),
  INDEX `fk_facilitadores_has_turmas_turmas1_idx` (`turmas_ id` ASC, `turmas_salas_ id` ASC) VISIBLE,
  INDEX `fk_facilitadores_has_turmas_facilitadores1_idx` (`facilitadores_ id` ASC) VISIBLE,
  CONSTRAINT `fk_facilitadores_has_turmas_facilitadores1`
    FOREIGN KEY (`facilitadores_ id`)
    REFERENCES `mydb`.`facilitadores` (` id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facilitadores_has_turmas_turmas1`
    FOREIGN KEY (`turmas_ id` , `turmas_salas_ id`)
    REFERENCES `mydb`.`turmas` (` id` , `salas_ id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
